In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Registro_de_Estaciones_de_Clasificación_y_Aprovechamiento-ECA.csv")

In [ ]:
columnas_numericas = [
    "Capacidad de Operación (Ton)",
    "Capacidad de Almacenamiento (Ton)",
    "Capacidad de Almacenamiento (m3)"
]

for col in columnas_numericas:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
        .pipe(pd.to_numeric, errors='coerce')
    )

df[columnas_numericas].dtypes
df.dtypes
df.head(30)

In [6]:
ecas_por_departamento = df.groupby(["Departamento"]).size().reset_index(name="Total_ECAs")

In [ ]:
ecas_por_departamento = df.groupby(["Departamento"]).agg(
    total_ecas=("Departamento", "size"),
    capacidad_total_ton=("Capacidad de Almacenamiento (Ton)", "sum")
).reset_index()

ecas_por_departamento

In [ ]:
import matplotlib.pyplot as plt

# Conteo de ECAs por departamento, ordenado de mayor a menor
ecas_por_departamento = (
    df.groupby("Departamento")
    .size()
    .reset_index(name="Total_ECAs")
    .sort_values("Total_ECAs", ascending=False)
)

print(ecas_por_departamento.to_string(index=False))

In [14]:
# Top 5 departamentos con más ECAs
top5 = ecas_por_departamento.head(5)
print("Top 5 departamentos con más ECAs:")
top5

Top 5 departamentos con más ECAs:

       Departamento  Total_ECAs
5      BOGOTÁ, D.C.        3082
14     CUNDINAMARCA         597
1         ANTIOQUIA         482
20             META         274
29  VALLE DEL CAUCA         209

In [10]:
!git config --global user.email "crisfore083@gmail.com"
!git config --global user.name "Cristian_Forero"

In [ ]:
!git remote -v
!git PRIMER_CODIGO_PROYECTO.ipynb.
!git commit -m "1_agrega análisis de ECAs por municipio con capacidad de almacenamiento"
!git push

In [13]:
menos5= ecas_por_departamento.tail(5)
print("top 5 departamentos con menos ecas")
menos5

top 5 departamentos con menos ecas

                                         Departamento  Total_ECAs
16                                           GUAVIARE           3
13                                              CHOCÓ           2
3   ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...           1
0                                            AMAZONAS           1
23                                           PUTUMAYO           1

In [19]:
!git add PRIMER_CODIGO_PROYECTO.ipynb
!git commit -m "2 agrega análisis de ECAs por departamento en top 5 de menos y mas ecas"
!git push

warning: in the working copy of 'PRIMER_CODIGO_PROYECTO.ipynb', LF will be replaced by CRLF the next time Git touches it

[main 227c96b] 2 agrega análisis de ECAs por departamento en top 5 de menos y mas ecas
 1 file changed, 89 insertions(+), 4 deletions(-)

To https://github.com/crisfore083-sudo/ECAS_SUI_PROYECTO.git
   07816a1..227c96b  main -> main